apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pfx-tls-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pfx-tls-operator
subjects:
  - kind: ServiceAccount
    name: pfx-tls-operator
    namespace: pfx-tls-system
